version: '3.3'
services:
  api:
    container_name: vidly
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      jwtPrivateKey: ${jwtPrivateKey:-secret}
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: